import { CareerNode } from './types';

export const INITIAL_CAREER_NODES: CareerNode[] = [
  {
    id: 'node-1',
    userId: 'user-1',
    nodeType: 'role',
    title: 'Staff Systems & Infrastructure Architect',
    org: 'Stripe / Cloud Scale',
    startDate: '2023-01',
    endDate: 'Present',
    situationTask: 'Led global egress infrastructure redesign across 12 availability zones.',
    action: 'Implemented Go-based proxy mesh with connection pooling and automated traffic failover.',
    result: 'Reduced tail latency p99 by 42% and saved $1.2M in annual cross-zone data transfer costs.',
    metrics: {
      dollarSaved: '$1.2M',
      scale: '12 AZs / 400k rps',
      latencyReduction: '42% p99',
    },
    tags: ['Go', 'Distributed Systems', 'Kubernetes', 'Networking', 'FinOps'],
    source: 'quick_add',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'node-2',
    userId: 'user-1',
    nodeType: 'project',
    title: 'High-Throughput Vector Retrieval Engine',
    org: 'Karma Open Source',
    startDate: '2023-08',
    endDate: '2023-12',
    situationTask: 'Standard embeddings lookup was encountering high memory usage in Node.js processes.',
    action: 'Engineered pgvector HNSW indexing with multi-tenant filtering and SIMD vector quantization.',
    result: 'Achieved sub-5ms cosine similarity search across 10M vectors with 85% reduced memory footprint.',
    metrics: {
      scale: '10M vectors',
      latencyReduction: '<5ms retrieval',
      percentGrowth: '+85% memory efficiency',
    },
    tags: ['PostgreSQL', 'pgvector', 'Rust', 'TypeScript', 'AI Search'],
    source: 'github_import',
    createdAt: '2024-02-10T14:30:00Z',
    updatedAt: '2024-02-10T14:30:00Z',
  },
  {
    id: 'node-3',
    userId: 'user-1',
    nodeType: 'achievement',
    title: 'Keynote Speaker: Building Resilient Microservices at Scale',
    org: 'GopherCon 2024',
    startDate: '2024-04',
    endDate: '2024-04',
    situationTask: 'Delivered technical deep-dive on memory allocations and zero-copy streaming in Go.',
    action: 'Presented live benchmarks and profiling techniques to an audience of 1,500+ backend engineers.',
    result: 'Rated top 3 presentation of the conference; open-source companion repo gained 2,400+ GitHub stars.',
    metrics: {
      scale: '1,500+ attendees',
      percentGrowth: '2.4k GitHub stars',
    },
    tags: ['Public Speaking', 'Go', 'Profiling', 'Community'],
    source: 'quick_add',
    createdAt: '2024-04-20T09:00:00Z',
    updatedAt: '2024-04-20T09:00:00Z',
  },
];
